//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/sink/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.sink;

@kotlin.jvm.JvmName("-initializewriteControlItemRsp")
public inline fun writeControlItemRsp(block: yandexcloud.datatransfer.dtextension.v0_2.sink.WriteControlItemRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp =
  yandexcloud.datatransfer.dtextension.v0_2.sink.WriteControlItemRspKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp.newBuilder()).apply { block() }._build()
public object WriteControlItemRspKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteInitConnectionRsp init_connection_rsp = 1;</code>
     */
    public var initConnectionRsp: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteInitConnectionRsp
      @JvmName("getInitConnectionRsp")
      get() = _builder.getInitConnectionRsp()
      @JvmName("setInitConnectionRsp")
      set(value) {
        _builder.setInitConnectionRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteInitConnectionRsp init_connection_rsp = 1;</code>
     */
    public fun clearInitConnectionRsp() {
      _builder.clearInitConnectionRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteInitConnectionRsp init_connection_rsp = 1;</code>
     * @return Whether the initConnectionRsp field is set.
     */
    public fun hasInitConnectionRsp(): kotlin.Boolean {
      return _builder.hasInitConnectionRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteDataItemRsp data_item_rsp = 2;</code>
     */
    public var dataItemRsp: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteDataItemRsp
      @JvmName("getDataItemRsp")
      get() = _builder.getDataItemRsp()
      @JvmName("setDataItemRsp")
      set(value) {
        _builder.setDataItemRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteDataItemRsp data_item_rsp = 2;</code>
     */
    public fun clearDataItemRsp() {
      _builder.clearDataItemRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteDataItemRsp data_item_rsp = 2;</code>
     * @return Whether the dataItemRsp field is set.
     */
    public fun hasDataItemRsp(): kotlin.Boolean {
      return _builder.hasDataItemRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotRsp begin_snapshot_rsp = 3;</code>
     */
    public var beginSnapshotRsp: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotRsp
      @JvmName("getBeginSnapshotRsp")
      get() = _builder.getBeginSnapshotRsp()
      @JvmName("setBeginSnapshotRsp")
      set(value) {
        _builder.setBeginSnapshotRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotRsp begin_snapshot_rsp = 3;</code>
     */
    public fun clearBeginSnapshotRsp() {
      _builder.clearBeginSnapshotRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotRsp begin_snapshot_rsp = 3;</code>
     * @return Whether the beginSnapshotRsp field is set.
     */
    public fun hasBeginSnapshotRsp(): kotlin.Boolean {
      return _builder.hasBeginSnapshotRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteDoneSnapshotRsp done_snapshot_rsp = 4;</code>
     */
    public var doneSnapshotRsp: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteDoneSnapshotRsp
      @JvmName("getDoneSnapshotRsp")
      get() = _builder.getDoneSnapshotRsp()
      @JvmName("setDoneSnapshotRsp")
      set(value) {
        _builder.setDoneSnapshotRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteDoneSnapshotRsp done_snapshot_rsp = 4;</code>
     */
    public fun clearDoneSnapshotRsp() {
      _builder.clearDoneSnapshotRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteDoneSnapshotRsp done_snapshot_rsp = 4;</code>
     * @return Whether the doneSnapshotRsp field is set.
     */
    public fun hasDoneSnapshotRsp(): kotlin.Boolean {
      return _builder.hasDoneSnapshotRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStartTransactionRsp write_start_transaction_rsp = 5;</code>
     */
    public var writeStartTransactionRsp: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionRsp
      @JvmName("getWriteStartTransactionRsp")
      get() = _builder.getWriteStartTransactionRsp()
      @JvmName("setWriteStartTransactionRsp")
      set(value) {
        _builder.setWriteStartTransactionRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStartTransactionRsp write_start_transaction_rsp = 5;</code>
     */
    public fun clearWriteStartTransactionRsp() {
      _builder.clearWriteStartTransactionRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStartTransactionRsp write_start_transaction_rsp = 5;</code>
     * @return Whether the writeStartTransactionRsp field is set.
     */
    public fun hasWriteStartTransactionRsp(): kotlin.Boolean {
      return _builder.hasWriteStartTransactionRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStopTransactionRsp write_stop_transaction_rsp = 6;</code>
     */
    public var writeStopTransactionRsp: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStopTransactionRsp
      @JvmName("getWriteStopTransactionRsp")
      get() = _builder.getWriteStopTransactionRsp()
      @JvmName("setWriteStopTransactionRsp")
      set(value) {
        _builder.setWriteStopTransactionRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStopTransactionRsp write_stop_transaction_rsp = 6;</code>
     */
    public fun clearWriteStopTransactionRsp() {
      _builder.clearWriteStopTransactionRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStopTransactionRsp write_stop_transaction_rsp = 6;</code>
     * @return Whether the writeStopTransactionRsp field is set.
     */
    public fun hasWriteStopTransactionRsp(): kotlin.Boolean {
      return _builder.hasWriteStopTransactionRsp()
    }
    public val controlItemRspCase: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp.ControlItemRspCase
      @JvmName("getControlItemRspCase")
      get() = _builder.getControlItemRspCase()

    public fun clearControlItemRsp() {
      _builder.clearControlItemRsp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp.copy(block: yandexcloud.datatransfer.dtextension.v0_2.sink.WriteControlItemRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp =
  yandexcloud.datatransfer.dtextension.v0_2.sink.WriteControlItemRspKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRspOrBuilder.initConnectionRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteInitConnectionRsp?
  get() = if (hasInitConnectionRsp()) getInitConnectionRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRspOrBuilder.dataItemRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteDataItemRsp?
  get() = if (hasDataItemRsp()) getDataItemRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRspOrBuilder.beginSnapshotRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotRsp?
  get() = if (hasBeginSnapshotRsp()) getBeginSnapshotRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRspOrBuilder.doneSnapshotRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteDoneSnapshotRsp?
  get() = if (hasDoneSnapshotRsp()) getDoneSnapshotRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRspOrBuilder.writeStartTransactionRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionRsp?
  get() = if (hasWriteStartTransactionRsp()) getWriteStartTransactionRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRspOrBuilder.writeStopTransactionRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStopTransactionRsp?
  get() = if (hasWriteStopTransactionRsp()) getWriteStopTransactionRsp() else null

