//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/sink/sink_service.proto

package yandexcloud.datatransfer.dtextension.v0_2.sink;

@kotlin.jvm.JvmName("-initializewriteRsp")
public inline fun writeRsp(block: yandexcloud.datatransfer.dtextension.v0_2.sink.WriteRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRsp =
  yandexcloud.datatransfer.dtextension.v0_2.sink.WriteRspKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRsp.newBuilder()).apply { block() }._build()
public object WriteRspKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRsp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRsp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRsp = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     */
    public var result: yandexcloud.datatransfer.dtextension.v0_2.Common.Result
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteControlItemRsp control_item_rsp = 2;</code>
     */
    public var controlItemRsp: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp
      @JvmName("getControlItemRsp")
      get() = _builder.getControlItemRsp()
      @JvmName("setControlItemRsp")
      set(value) {
        _builder.setControlItemRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteControlItemRsp control_item_rsp = 2;</code>
     */
    public fun clearControlItemRsp() {
      _builder.clearControlItemRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteControlItemRsp control_item_rsp = 2;</code>
     * @return Whether the controlItemRsp field is set.
     */
    public fun hasControlItemRsp(): kotlin.Boolean {
      return _builder.hasControlItemRsp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRsp.copy(block: yandexcloud.datatransfer.dtextension.v0_2.sink.WriteRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRsp =
  yandexcloud.datatransfer.dtextension.v0_2.sink.WriteRspKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRspOrBuilder.resultOrNull: yandexcloud.datatransfer.dtextension.v0_2.Common.Result?
  get() = if (hasResult()) getResult() else null

val yandexcloud.datatransfer.dtextension.v0_2.sink.SinkServiceOuterClass.WriteRspOrBuilder.controlItemRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteControlItemRsp?
  get() = if (hasControlItemRsp()) getControlItemRsp() else null

