//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/sink/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.sink;

@kotlin.jvm.JvmName("-initializewriteBeginSnapshotReq")
public inline fun writeBeginSnapshotReq(block: yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReq =
  yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReq.newBuilder()).apply { block() }._build()
public object WriteBeginSnapshotReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReq = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Table table = 1;</code>
     */
    public var table: yandexcloud.datatransfer.dtextension.v0_2.Data.Table
      @JvmName("getTable")
      get() = _builder.getTable()
      @JvmName("setTable")
      set(value) {
        _builder.setTable(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Table table = 1;</code>
     */
    public fun clearTable() {
      _builder.clearTable()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Table table = 1;</code>
     * @return Whether the table field is set.
     */
    public fun hasTable(): kotlin.Boolean {
      return _builder.hasTable()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotReq.CleanupType cleanup_type = 2;</code>
     */
    public var cleanupType: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReq.CleanupType
      @JvmName("getCleanupType")
      get() = _builder.getCleanupType()
      @JvmName("setCleanupType")
      set(value) {
        _builder.setCleanupType(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotReq.CleanupType cleanup_type = 2;</code>
     */
    public fun clearCleanupType() {
      _builder.clearCleanupType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReq =
  yandexcloud.datatransfer.dtextension.v0_2.sink.WriteBeginSnapshotReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteBeginSnapshotReqOrBuilder.tableOrNull: yandexcloud.datatransfer.dtextension.v0_2.Data.Table?
  get() = if (hasTable()) getTable() else null

