//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/sink/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.sink;

@kotlin.jvm.JvmName("-initializewriteStartTransactionReq")
public inline fun writeStartTransactionReq(block: yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStartTransactionReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionReq =
  yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStartTransactionReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionReq.newBuilder()).apply { block() }._build()
public object WriteStartTransactionReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionReq = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStartTransactionReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.sink.Control.WriteStartTransactionReq =
  yandexcloud.datatransfer.dtextension.v0_2.sink.WriteStartTransactionReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

