//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/data.proto

package yandexcloud.datatransfer.dtextension.v0_2;

@kotlin.jvm.JvmName("-initializechangeItem")
public inline fun changeItem(block: yandexcloud.datatransfer.dtextension.v0_2.ChangeItemKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItem =
  yandexcloud.datatransfer.dtextension.v0_2.ChangeItemKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItem.newBuilder()).apply { block() }._build()
public object ChangeItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItem = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.DataChangeItem data_change_item = 1;</code>
     */
    public var dataChangeItem: yandexcloud.datatransfer.dtextension.v0_2.Data.DataChangeItem
      @JvmName("getDataChangeItem")
      get() = _builder.getDataChangeItem()
      @JvmName("setDataChangeItem")
      set(value) {
        _builder.setDataChangeItem(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.DataChangeItem data_change_item = 1;</code>
     */
    public fun clearDataChangeItem() {
      _builder.clearDataChangeItem()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.DataChangeItem data_change_item = 1;</code>
     * @return Whether the dataChangeItem field is set.
     */
    public fun hasDataChangeItem(): kotlin.Boolean {
      return _builder.hasDataChangeItem()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.HomoChangeItem ddl_change_item = 2;</code>
     */
    public var ddlChangeItem: yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem
      @JvmName("getDdlChangeItem")
      get() = _builder.getDdlChangeItem()
      @JvmName("setDdlChangeItem")
      set(value) {
        _builder.setDdlChangeItem(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.HomoChangeItem ddl_change_item = 2;</code>
     */
    public fun clearDdlChangeItem() {
      _builder.clearDdlChangeItem()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.HomoChangeItem ddl_change_item = 2;</code>
     * @return Whether the ddlChangeItem field is set.
     */
    public fun hasDdlChangeItem(): kotlin.Boolean {
      return _builder.hasDdlChangeItem()
    }
    public val changeItemCase: yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItem.ChangeItemCase
      @JvmName("getChangeItemCase")
      get() = _builder.getChangeItemCase()

    public fun clearChangeItem() {
      _builder.clearChangeItem()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItem.copy(block: yandexcloud.datatransfer.dtextension.v0_2.ChangeItemKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItem =
  yandexcloud.datatransfer.dtextension.v0_2.ChangeItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItemOrBuilder.dataChangeItemOrNull: yandexcloud.datatransfer.dtextension.v0_2.Data.DataChangeItem?
  get() = if (hasDataChangeItem()) getDataChangeItem() else null

val yandexcloud.datatransfer.dtextension.v0_2.Data.ChangeItemOrBuilder.ddlChangeItemOrNull: yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem?
  get() = if (hasDdlChangeItem()) getDdlChangeItem() else null

