//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/common.proto

package yandexcloud.datatransfer.dtextension.v0_2;

@kotlin.jvm.JvmName("-initializecursor")
public inline fun cursor(block: yandexcloud.datatransfer.dtextension.v0_2.CursorKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor =
  yandexcloud.datatransfer.dtextension.v0_2.CursorKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor.newBuilder()).apply { block() }._build()
public object CursorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnCursor column_cursor = 1;</code>
     */
    public var columnCursor: yandexcloud.datatransfer.dtextension.v0_2.Common.ColumnCursor
      @JvmName("getColumnCursor")
      get() = _builder.getColumnCursor()
      @JvmName("setColumnCursor")
      set(value) {
        _builder.setColumnCursor(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnCursor column_cursor = 1;</code>
     */
    public fun clearColumnCursor() {
      _builder.clearColumnCursor()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnCursor column_cursor = 1;</code>
     * @return Whether the columnCursor field is set.
     */
    public fun hasColumnCursor(): kotlin.Boolean {
      return _builder.hasColumnCursor()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.LineCursor line_cursor = 2;</code>
     */
    public var lineCursor: yandexcloud.datatransfer.dtextension.v0_2.Common.LineCursor
      @JvmName("getLineCursor")
      get() = _builder.getLineCursor()
      @JvmName("setLineCursor")
      set(value) {
        _builder.setLineCursor(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.LineCursor line_cursor = 2;</code>
     */
    public fun clearLineCursor() {
      _builder.clearLineCursor()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.LineCursor line_cursor = 2;</code>
     * @return Whether the lineCursor field is set.
     */
    public fun hasLineCursor(): kotlin.Boolean {
      return _builder.hasLineCursor()
    }
    public val cursorCase: yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor.CursorCase
      @JvmName("getCursorCase")
      get() = _builder.getCursorCase()

    public fun clearCursor() {
      _builder.clearCursor()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor.copy(block: yandexcloud.datatransfer.dtextension.v0_2.CursorKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor =
  yandexcloud.datatransfer.dtextension.v0_2.CursorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.Common.CursorOrBuilder.columnCursorOrNull: yandexcloud.datatransfer.dtextension.v0_2.Common.ColumnCursor?
  get() = if (hasColumnCursor()) getColumnCursor() else null

val yandexcloud.datatransfer.dtextension.v0_2.Common.CursorOrBuilder.lineCursorOrNull: yandexcloud.datatransfer.dtextension.v0_2.Common.LineCursor?
  get() = if (hasLineCursor()) getLineCursor() else null

