//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/data.proto

package yandexcloud.datatransfer.dtextension.v0_2;

@kotlin.jvm.JvmName("-initializehomoChangeItem")
public inline fun homoChangeItem(block: yandexcloud.datatransfer.dtextension.v0_2.HomoChangeItemKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem =
  yandexcloud.datatransfer.dtextension.v0_2.HomoChangeItemKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem.newBuilder()).apply { block() }._build()
public object HomoChangeItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem = _builder.build()

    /**
     * <code>string connector_id = 1;</code>
     */
    public var connectorId: kotlin.String
      @JvmName("getConnectorId")
      get() = _builder.getConnectorId()
      @JvmName("setConnectorId")
      set(value) {
        _builder.setConnectorId(value)
      }
    /**
     * <code>string connector_id = 1;</code>
     */
    public fun clearConnectorId() {
      _builder.clearConnectorId()
    }

    /**
     * <code>bytes change_item = 2;</code>
     */
    public var changeItem: com.google.protobuf.ByteString
      @JvmName("getChangeItem")
      get() = _builder.getChangeItem()
      @JvmName("setChangeItem")
      set(value) {
        _builder.setChangeItem(value)
      }
    /**
     * <code>bytes change_item = 2;</code>
     */
    public fun clearChangeItem() {
      _builder.clearChangeItem()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem.copy(block: yandexcloud.datatransfer.dtextension.v0_2.HomoChangeItemKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.HomoChangeItem =
  yandexcloud.datatransfer.dtextension.v0_2.HomoChangeItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

