//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/data.proto

package yandexcloud.datatransfer.dtextension.v0_2;

@kotlin.jvm.JvmName("-initializeparquet")
public inline fun parquet(block: yandexcloud.datatransfer.dtextension.v0_2.ParquetKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.Parquet =
  yandexcloud.datatransfer.dtextension.v0_2.ParquetKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.Data.Parquet.newBuilder()).apply { block() }._build()
public object ParquetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.Data.Parquet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.Data.Parquet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.Data.Parquet = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParquetValuesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ParquetValue parquet_values = 1;</code>
     */
     public val parquetValues: com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue, ParquetValuesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getParquetValuesList()
      )
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ParquetValue parquet_values = 1;</code>
     * @param value The parquetValues to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addParquetValues")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue, ParquetValuesProxy>.add(value: yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue) {
      _builder.addParquetValues(value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ParquetValue parquet_values = 1;</code>
     * @param value The parquetValues to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignParquetValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue, ParquetValuesProxy>.plusAssign(value: yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue) {
      add(value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ParquetValue parquet_values = 1;</code>
     * @param values The parquetValues to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllParquetValues")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue, ParquetValuesProxy>.addAll(values: kotlin.collections.Iterable<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue>) {
      _builder.addAllParquetValues(values)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ParquetValue parquet_values = 1;</code>
     * @param values The parquetValues to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllParquetValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue, ParquetValuesProxy>.plusAssign(values: kotlin.collections.Iterable<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue>) {
      addAll(values)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ParquetValue parquet_values = 1;</code>
     * @param index The index to set the value at.
     * @param value The parquetValues to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setParquetValues")
    public operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue, ParquetValuesProxy>.set(index: kotlin.Int, value: yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue) {
      _builder.setParquetValues(index, value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ParquetValue parquet_values = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearParquetValues")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ParquetValue, ParquetValuesProxy>.clear() {
      _builder.clearParquetValues()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.Data.Parquet.copy(block: yandexcloud.datatransfer.dtextension.v0_2.ParquetKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.Parquet =
  yandexcloud.datatransfer.dtextension.v0_2.ParquetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

