//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/data.proto

package yandexcloud.datatransfer.dtextension.v0_2;

@kotlin.jvm.JvmName("-initializeplainRow")
public inline fun plainRow(block: yandexcloud.datatransfer.dtextension.v0_2.PlainRowKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.PlainRow =
  yandexcloud.datatransfer.dtextension.v0_2.PlainRowKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.Data.PlainRow.newBuilder()).apply { block() }._build()
public object PlainRowKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.Data.PlainRow.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.Data.PlainRow.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.Data.PlainRow = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ValuesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ColumnValue values = 1;</code>
     */
     public val values: com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue, ValuesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getValuesList()
      )
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ColumnValue values = 1;</code>
     * @param value The values to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addValues")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue, ValuesProxy>.add(value: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue) {
      _builder.addValues(value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ColumnValue values = 1;</code>
     * @param value The values to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue, ValuesProxy>.plusAssign(value: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue) {
      add(value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ColumnValue values = 1;</code>
     * @param values The values to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllValues")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue, ValuesProxy>.addAll(values: kotlin.collections.Iterable<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue>) {
      _builder.addAllValues(values)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ColumnValue values = 1;</code>
     * @param values The values to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue, ValuesProxy>.plusAssign(values: kotlin.collections.Iterable<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue>) {
      addAll(values)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ColumnValue values = 1;</code>
     * @param index The index to set the value at.
     * @param value The values to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setValues")
    public operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue, ValuesProxy>.set(index: kotlin.Int, value: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue) {
      _builder.setValues(index, value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.ColumnValue values = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearValues")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue, ValuesProxy>.clear() {
      _builder.clearValues()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.Data.PlainRow.copy(block: yandexcloud.datatransfer.dtextension.v0_2.PlainRowKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.PlainRow =
  yandexcloud.datatransfer.dtextension.v0_2.PlainRowKt.Dsl._create(this.toBuilder()).apply { block() }._build()

