//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/common.proto

package yandexcloud.datatransfer.dtextension.v0_2;

@kotlin.jvm.JvmName("-initializeresult")
public inline fun result(block: yandexcloud.datatransfer.dtextension.v0_2.ResultKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Common.Result =
  yandexcloud.datatransfer.dtextension.v0_2.ResultKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.Common.Result.newBuilder()).apply { block() }._build()
public object ResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.Common.Result.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.Common.Result.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.Common.Result = _builder.build()

    /**
     * <code>bool ok = 1;</code>
     */
    public var ok: kotlin.Boolean
      @JvmName("getOk")
      get() = _builder.getOk()
      @JvmName("setOk")
      set(value) {
        _builder.setOk(value)
      }
    /**
     * <code>bool ok = 1;</code>
     */
    public fun clearOk() {
      _builder.clearOk()
    }

    /**
     * <code>string error = 2;</code>
     */
    public var error: kotlin.String
      @JvmName("getError")
      get() = _builder.getError()
      @JvmName("setError")
      set(value) {
        _builder.setError(value)
      }
    /**
     * <code>string error = 2;</code>
     */
    public fun clearError() {
      _builder.clearError()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.Common.Result.copy(block: yandexcloud.datatransfer.dtextension.v0_2.ResultKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Common.Result =
  yandexcloud.datatransfer.dtextension.v0_2.ResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

