//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/data.proto

package yandexcloud.datatransfer.dtextension.v0_2;

@kotlin.jvm.JvmName("-initializeschema")
public inline fun schema(block: yandexcloud.datatransfer.dtextension.v0_2.SchemaKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.Schema =
  yandexcloud.datatransfer.dtextension.v0_2.SchemaKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.Data.Schema.newBuilder()).apply { block() }._build()
public object SchemaKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.Data.Schema.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.Data.Schema.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.Data.Schema = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ColumnsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.Column columns = 1;</code>
     */
     public val columns: com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.Column, ColumnsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getColumnsList()
      )
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.Column columns = 1;</code>
     * @param value The columns to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addColumns")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.Column, ColumnsProxy>.add(value: yandexcloud.datatransfer.dtextension.v0_2.Data.Column) {
      _builder.addColumns(value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.Column columns = 1;</code>
     * @param value The columns to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignColumns")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.Column, ColumnsProxy>.plusAssign(value: yandexcloud.datatransfer.dtextension.v0_2.Data.Column) {
      add(value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.Column columns = 1;</code>
     * @param values The columns to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllColumns")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.Column, ColumnsProxy>.addAll(values: kotlin.collections.Iterable<yandexcloud.datatransfer.dtextension.v0_2.Data.Column>) {
      _builder.addAllColumns(values)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.Column columns = 1;</code>
     * @param values The columns to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllColumns")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.Column, ColumnsProxy>.plusAssign(values: kotlin.collections.Iterable<yandexcloud.datatransfer.dtextension.v0_2.Data.Column>) {
      addAll(values)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.Column columns = 1;</code>
     * @param index The index to set the value at.
     * @param value The columns to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setColumns")
    public operator fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.Column, ColumnsProxy>.set(index: kotlin.Int, value: yandexcloud.datatransfer.dtextension.v0_2.Data.Column) {
      _builder.setColumns(index, value)
    }
    /**
     * <code>repeated .yandexcloud.datatransfer.dtextension.v0_2.Column columns = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearColumns")
    public fun com.google.protobuf.kotlin.DslList<yandexcloud.datatransfer.dtextension.v0_2.Data.Column, ColumnsProxy>.clear() {
      _builder.clearColumns()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.Data.Schema.copy(block: yandexcloud.datatransfer.dtextension.v0_2.SchemaKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Data.Schema =
  yandexcloud.datatransfer.dtextension.v0_2.SchemaKt.Dsl._create(this.toBuilder()).apply { block() }._build()

