//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/common.proto

package yandexcloud.datatransfer.dtextension.v0_2;

@kotlin.jvm.JvmName("-initializespecReq")
public inline fun specReq(block: yandexcloud.datatransfer.dtextension.v0_2.SpecReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Common.SpecReq =
  yandexcloud.datatransfer.dtextension.v0_2.SpecReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.Common.SpecReq.newBuilder()).apply { block() }._build()
public object SpecReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.Common.SpecReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.Common.SpecReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.Common.SpecReq = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.Common.SpecReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.SpecReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.Common.SpecReq =
  yandexcloud.datatransfer.dtextension.v0_2.SpecReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

