// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/v0_2/common.proto

package v0_2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SpecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpecReq) Reset() {
	*x = SpecReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecReq) ProtoMessage() {}

func (x *SpecReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecReq.ProtoReflect.Descriptor instead.
func (*SpecReq) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{1}
}

// SpecRsp is response of Spec handle that declares setting that endpoint has
// with the use of JSON schema
type SpecRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	JsonSpec string  `protobuf:"bytes,2,opt,name=json_spec,json=jsonSpec,proto3" json:"json_spec,omitempty"`
}

func (x *SpecRsp) Reset() {
	*x = SpecRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecRsp) ProtoMessage() {}

func (x *SpecRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecRsp.ProtoReflect.Descriptor instead.
func (*SpecRsp) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{2}
}

func (x *SpecRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SpecRsp) GetJsonSpec() string {
	if x != nil {
		return x.JsonSpec
	}
	return ""
}

type CheckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// this JSON should comply to SpecRsp.json_spec returned by 'Spec' handle
	JsonSettings string `protobuf:"bytes,1,opt,name=json_settings,json=jsonSettings,proto3" json:"json_settings,omitempty"`
}

func (x *CheckReq) Reset() {
	*x = CheckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReq) ProtoMessage() {}

func (x *CheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReq.ProtoReflect.Descriptor instead.
func (*CheckReq) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{3}
}

func (x *CheckReq) GetJsonSettings() string {
	if x != nil {
		return x.JsonSettings
	}
	return ""
}

type CheckRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CheckRsp) Reset() {
	*x = CheckRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRsp) ProtoMessage() {}

func (x *CheckRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRsp.ProtoReflect.Descriptor instead.
func (*CheckRsp) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

// InitConnectionReq -- is the first streaming message that established bidirectional connection for
// Read, Stream and Write gRPC calls. It signals endpoint code to initiate
// connection with source database with settings used by user
// client_id -- when non empty, used to identify client that may perform multiple operations on service.
// You may ignore this field if you make implementation for single client
type InitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonSettings string `protobuf:"bytes,1,opt,name=json_settings,json=jsonSettings,proto3" json:"json_settings,omitempty"`
	ClientId     string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *InitReq) Reset() {
	*x = InitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReq) ProtoMessage() {}

func (x *InitReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReq.ProtoReflect.Descriptor instead.
func (*InitReq) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{5}
}

func (x *InitReq) GetJsonSettings() string {
	if x != nil {
		return x.JsonSettings
	}
	return ""
}

func (x *InitReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// client_id -- generated client id, if it was empty in `InitConnectionReq`
// You may ignore this field if you make implementation for single client
type InitRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *InitRsp) Reset() {
	*x = InitRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRsp) ProtoMessage() {}

func (x *InitRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRsp.ProtoReflect.Descriptor instead.
func (*InitRsp) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{6}
}

func (x *InitRsp) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// this message represents an interval in form [from; to]
// each of begin or end of the interval can be excluded with
// "exclude_from" and "exclude_to" flags
type DataRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// absence of 'from' field means -oo
	From *ColumnValue `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// absence of 'to' field means +oo
	To *ColumnValue `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// explicit setting "exclude_from" to true when "descending == false" in `ColumnCursor` should be done,
	// if column of the data range is itself primary key, not the part of some compound primary key or unique index.
	// Thus, you can make exactly once semantics, where 'from' meaning last committed message by the client
	ExcludeFrom bool `protobuf:"varint,3,opt,name=exclude_from,json=excludeFrom,proto3" json:"exclude_from,omitempty"`
	// explicit setting "exclude_to" to true when "descending == true" in `ColumnCursor`  should be done,
	// if column of the data range is itself primary key, not the part of some compound primary key or unique index.
	// Thus, you can make exactly once semantics, where 'to' meaning last committed message by the client
	ExcludeTo bool `protobuf:"varint,4,opt,name=exclude_to,json=excludeTo,proto3" json:"exclude_to,omitempty"`
}

func (x *DataRange) Reset() {
	*x = DataRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRange) ProtoMessage() {}

func (x *DataRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRange.ProtoReflect.Descriptor instead.
func (*DataRange) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{7}
}

func (x *DataRange) GetFrom() *ColumnValue {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DataRange) GetTo() *ColumnValue {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *DataRange) GetExcludeFrom() bool {
	if x != nil {
		return x.ExcludeFrom
	}
	return false
}

func (x *DataRange) GetExcludeTo() bool {
	if x != nil {
		return x.ExcludeTo
	}
	return false
}

type ColumnCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column    *Column    `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	DataRange *DataRange `protobuf:"bytes,2,opt,name=data_range,json=dataRange,proto3" json:"data_range,omitempty"`
	// the default upload behaviour is increasing. Specify this in order to change behaviour
	Descending bool `protobuf:"varint,3,opt,name=descending,proto3" json:"descending,omitempty"`
}

func (x *ColumnCursor) Reset() {
	*x = ColumnCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnCursor) ProtoMessage() {}

func (x *ColumnCursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnCursor.ProtoReflect.Descriptor instead.
func (*ColumnCursor) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{8}
}

func (x *ColumnCursor) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *ColumnCursor) GetDataRange() *DataRange {
	if x != nil {
		return x.DataRange
	}
	return nil
}

func (x *ColumnCursor) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

// note, that there is difference from DataRange, because
// one can easily do arithmetics on this datatype:
//    [from; to] -> [from; m] U [m + 1; to]
type LineCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromInclusive uint64 `protobuf:"varint,1,opt,name=from_inclusive,json=fromInclusive,proto3" json:"from_inclusive,omitempty"`
	ToInclusive   uint64 `protobuf:"varint,2,opt,name=to_inclusive,json=toInclusive,proto3" json:"to_inclusive,omitempty"`
}

func (x *LineCursor) Reset() {
	*x = LineCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineCursor) ProtoMessage() {}

func (x *LineCursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineCursor.ProtoReflect.Descriptor instead.
func (*LineCursor) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{9}
}

func (x *LineCursor) GetFromInclusive() uint64 {
	if x != nil {
		return x.FromInclusive
	}
	return 0
}

func (x *LineCursor) GetToInclusive() uint64 {
	if x != nil {
		return x.ToInclusive
	}
	return 0
}

// this cursor denotes empty set remaining
type EndCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndCursor) Reset() {
	*x = EndCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCursor) ProtoMessage() {}

func (x *EndCursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCursor.ProtoReflect.Descriptor instead.
func (*EndCursor) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{10}
}

type Cursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Cursor:
	//	*Cursor_ColumnCursor
	//	*Cursor_LineCursor
	//	*Cursor_EndCursor
	Cursor isCursor_Cursor `protobuf_oneof:"cursor"`
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v0_2_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0_2_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_api_v0_2_common_proto_rawDescGZIP(), []int{11}
}

func (m *Cursor) GetCursor() isCursor_Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (x *Cursor) GetColumnCursor() *ColumnCursor {
	if x, ok := x.GetCursor().(*Cursor_ColumnCursor); ok {
		return x.ColumnCursor
	}
	return nil
}

func (x *Cursor) GetLineCursor() *LineCursor {
	if x, ok := x.GetCursor().(*Cursor_LineCursor); ok {
		return x.LineCursor
	}
	return nil
}

func (x *Cursor) GetEndCursor() *EndCursor {
	if x, ok := x.GetCursor().(*Cursor_EndCursor); ok {
		return x.EndCursor
	}
	return nil
}

type isCursor_Cursor interface {
	isCursor_Cursor()
}

type Cursor_ColumnCursor struct {
	ColumnCursor *ColumnCursor `protobuf:"bytes,1,opt,name=column_cursor,json=columnCursor,proto3,oneof"`
}

type Cursor_LineCursor struct {
	LineCursor *LineCursor `protobuf:"bytes,2,opt,name=line_cursor,json=lineCursor,proto3,oneof"`
}

type Cursor_EndCursor struct {
	EndCursor *EndCursor `protobuf:"bytes,3,opt,name=end_cursor,json=endCursor,proto3,oneof"`
}

func (*Cursor_ColumnCursor) isCursor_Cursor() {}

func (*Cursor_LineCursor) isCursor_Cursor() {}

func (*Cursor_EndCursor) isCursor_Cursor() {}

var File_api_v0_2_common_proto protoreflect.FileDescriptor

var file_api_v0_2_common_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x5f, 0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30,
	0x5f, 0x32, 0x1a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x5f, 0x32, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x65, 0x71, 0x22, 0x71, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x52, 0x73, 0x70, 0x12, 0x49, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x5f, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x73, 0x6f, 0x6e,
	0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f,
	0x6e, 0x53, 0x70, 0x65, 0x63, 0x22, 0x2f, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x12, 0x23, 0x0a, 0x0d, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6a, 0x73, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x55, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52,
	0x73, 0x70, 0x12, 0x49, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x31, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x64, 0x74,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x5f, 0x32, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4b, 0x0a,
	0x07, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x0d, 0x6a, 0x73, 0x6f, 0x6e,
	0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6a, 0x73, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x07, 0x49, 0x6e,
	0x69, 0x74, 0x52, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0xe1, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x4a, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x5f, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x46, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65,
	0x78, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x30, 0x5f, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x65, 0x78, 0x63, 0x6c,
	0x75, 0x64, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x54, 0x6f, 0x22, 0xce, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x49, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x30, 0x5f, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x12, 0x53, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30,
	0x5f, 0x32, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x65, 0x73,
	0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x56, 0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x65, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x66,
	0x72, 0x6f, 0x6d, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x6f, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22,
	0x0b, 0x0a, 0x09, 0x45, 0x6e, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0xa3, 0x02, 0x0a,
	0x06, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x5e, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x5f, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x58, 0x0a, 0x0b, 0x6c, 0x69, 0x6e, 0x65, 0x5f,
	0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x79,
	0x61, 0x6e, 0x64, 0x65, 0x78, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x5f, 0x32, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x12, 0x55, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x2e, 0x64, 0x74, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x5f,
	0x32, 0x2e, 0x45, 0x6e, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x09, 0x65,
	0x6e, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x42, 0x27, 0x5a, 0x25, 0x6b, 0x72, 0x79, 0x31, 0x32, 0x37, 0x2e, 0x72, 0x75, 0x2f,
	0x64, 0x74, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x5f, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_v0_2_common_proto_rawDescOnce sync.Once
	file_api_v0_2_common_proto_rawDescData = file_api_v0_2_common_proto_rawDesc
)

func file_api_v0_2_common_proto_rawDescGZIP() []byte {
	file_api_v0_2_common_proto_rawDescOnce.Do(func() {
		file_api_v0_2_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v0_2_common_proto_rawDescData)
	})
	return file_api_v0_2_common_proto_rawDescData
}

var file_api_v0_2_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v0_2_common_proto_goTypes = []interface{}{
	(*Result)(nil),       // 0: yandexcloud.datatransfer.dtextension.v0_2.Result
	(*SpecReq)(nil),      // 1: yandexcloud.datatransfer.dtextension.v0_2.SpecReq
	(*SpecRsp)(nil),      // 2: yandexcloud.datatransfer.dtextension.v0_2.SpecRsp
	(*CheckReq)(nil),     // 3: yandexcloud.datatransfer.dtextension.v0_2.CheckReq
	(*CheckRsp)(nil),     // 4: yandexcloud.datatransfer.dtextension.v0_2.CheckRsp
	(*InitReq)(nil),      // 5: yandexcloud.datatransfer.dtextension.v0_2.InitReq
	(*InitRsp)(nil),      // 6: yandexcloud.datatransfer.dtextension.v0_2.InitRsp
	(*DataRange)(nil),    // 7: yandexcloud.datatransfer.dtextension.v0_2.DataRange
	(*ColumnCursor)(nil), // 8: yandexcloud.datatransfer.dtextension.v0_2.ColumnCursor
	(*LineCursor)(nil),   // 9: yandexcloud.datatransfer.dtextension.v0_2.LineCursor
	(*EndCursor)(nil),    // 10: yandexcloud.datatransfer.dtextension.v0_2.EndCursor
	(*Cursor)(nil),       // 11: yandexcloud.datatransfer.dtextension.v0_2.Cursor
	(*ColumnValue)(nil),  // 12: yandexcloud.datatransfer.dtextension.v0_2.ColumnValue
	(*Column)(nil),       // 13: yandexcloud.datatransfer.dtextension.v0_2.Column
}
var file_api_v0_2_common_proto_depIdxs = []int32{
	0,  // 0: yandexcloud.datatransfer.dtextension.v0_2.SpecRsp.result:type_name -> yandexcloud.datatransfer.dtextension.v0_2.Result
	0,  // 1: yandexcloud.datatransfer.dtextension.v0_2.CheckRsp.result:type_name -> yandexcloud.datatransfer.dtextension.v0_2.Result
	12, // 2: yandexcloud.datatransfer.dtextension.v0_2.DataRange.from:type_name -> yandexcloud.datatransfer.dtextension.v0_2.ColumnValue
	12, // 3: yandexcloud.datatransfer.dtextension.v0_2.DataRange.to:type_name -> yandexcloud.datatransfer.dtextension.v0_2.ColumnValue
	13, // 4: yandexcloud.datatransfer.dtextension.v0_2.ColumnCursor.column:type_name -> yandexcloud.datatransfer.dtextension.v0_2.Column
	7,  // 5: yandexcloud.datatransfer.dtextension.v0_2.ColumnCursor.data_range:type_name -> yandexcloud.datatransfer.dtextension.v0_2.DataRange
	8,  // 6: yandexcloud.datatransfer.dtextension.v0_2.Cursor.column_cursor:type_name -> yandexcloud.datatransfer.dtextension.v0_2.ColumnCursor
	9,  // 7: yandexcloud.datatransfer.dtextension.v0_2.Cursor.line_cursor:type_name -> yandexcloud.datatransfer.dtextension.v0_2.LineCursor
	10, // 8: yandexcloud.datatransfer.dtextension.v0_2.Cursor.end_cursor:type_name -> yandexcloud.datatransfer.dtextension.v0_2.EndCursor
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_v0_2_common_proto_init() }
func file_api_v0_2_common_proto_init() {
	if File_api_v0_2_common_proto != nil {
		return
	}
	file_api_v0_2_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v0_2_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v0_2_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v0_2_common_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*Cursor_ColumnCursor)(nil),
		(*Cursor_LineCursor)(nil),
		(*Cursor_EndCursor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v0_2_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v0_2_common_proto_goTypes,
		DependencyIndexes: file_api_v0_2_common_proto_depIdxs,
		MessageInfos:      file_api_v0_2_common_proto_msgTypes,
	}.Build()
	File_api_v0_2_common_proto = out.File
	file_api_v0_2_common_proto_rawDesc = nil
	file_api_v0_2_common_proto_goTypes = nil
	file_api_v0_2_common_proto_depIdxs = nil
}
