//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializecheckLsnReq")
public inline fun checkLsnReq(block: yandexcloud.datatransfer.dtextension.v0_2.source.CheckLsnReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.CheckLsnReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq.newBuilder()).apply { block() }._build()
public object CheckLsnReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 1;</code>
     */
    public var lsn: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue
      @JvmName("getLsn")
      get() = _builder.getLsn()
      @JvmName("setLsn")
      set(value) {
        _builder.setLsn(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 1;</code>
     */
    public fun clearLsn() {
      _builder.clearLsn()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 1;</code>
     * @return Whether the lsn field is set.
     */
    public fun hasLsn(): kotlin.Boolean {
      return _builder.hasLsn()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.CheckLsnReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.CheckLsnReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReqOrBuilder.lsnOrNull: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue?
  get() = if (hasLsn()) getLsn() else null

