//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializecursorRsp")
public inline fun cursorRsp(block: yandexcloud.datatransfer.dtextension.v0_2.source.CursorRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp =
  yandexcloud.datatransfer.dtextension.v0_2.source.CursorRspKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp.newBuilder()).apply { block() }._build()
public object CursorRspKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     */
    public var result: yandexcloud.datatransfer.dtextension.v0_2.Common.Result
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Cursor cursor = 2;</code>
     */
    public var cursor: yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor
      @JvmName("getCursor")
      get() = _builder.getCursor()
      @JvmName("setCursor")
      set(value) {
        _builder.setCursor(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Cursor cursor = 2;</code>
     */
    public fun clearCursor() {
      _builder.clearCursor()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Cursor cursor = 2;</code>
     * @return Whether the cursor field is set.
     */
    public fun hasCursor(): kotlin.Boolean {
      return _builder.hasCursor()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.CursorRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp =
  yandexcloud.datatransfer.dtextension.v0_2.source.CursorRspKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRspOrBuilder.resultOrNull: yandexcloud.datatransfer.dtextension.v0_2.Common.Result?
  get() = if (hasResult()) getResult() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRspOrBuilder.cursorOrNull: yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor?
  get() = if (hasCursor()) getCursor() else null

