//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/source_service.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializediscoverReq")
public inline fun discoverReq(block: yandexcloud.datatransfer.dtextension.v0_2.source.DiscoverReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.DiscoverReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.DiscoverReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.DiscoverReq.newBuilder()).apply { block() }._build()
public object DiscoverReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.DiscoverReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.DiscoverReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.DiscoverReq = _builder.build()

    /**
     * <pre>
     * this JSON should comply to SpecRsp.json_spec returned by 'Spec' handle
     * and should be verified by Check rpc handle as compliant
     * </pre>
     *
     * <code>string json_settings = 1;</code>
     */
    public var jsonSettings: kotlin.String
      @JvmName("getJsonSettings")
      get() = _builder.getJsonSettings()
      @JvmName("setJsonSettings")
      set(value) {
        _builder.setJsonSettings(value)
      }
    /**
     * <pre>
     * this JSON should comply to SpecRsp.json_spec returned by 'Spec' handle
     * and should be verified by Check rpc handle as compliant
     * </pre>
     *
     * <code>string json_settings = 1;</code>
     */
    public fun clearJsonSettings() {
      _builder.clearJsonSettings()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.DiscoverReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.DiscoverReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.DiscoverReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.DiscoverReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

