//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializedoneShardReq")
public inline fun doneShardReq(block: yandexcloud.datatransfer.dtextension.v0_2.source.DoneShardReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneShardReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.DoneShardReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneShardReq.newBuilder()).apply { block() }._build()
public object DoneShardReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneShardReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneShardReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneShardReq = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneShardReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.DoneShardReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneShardReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.DoneShardReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

