//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializefixLsnRsp")
public inline fun fixLsnRsp(block: yandexcloud.datatransfer.dtextension.v0_2.source.FixLsnRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRsp =
  yandexcloud.datatransfer.dtextension.v0_2.source.FixLsnRspKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRsp.newBuilder()).apply { block() }._build()
public object FixLsnRspKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRsp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRsp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRsp = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     */
    public var result: yandexcloud.datatransfer.dtextension.v0_2.Common.Result
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 2;</code>
     */
    public var lsn: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue
      @JvmName("getLsn")
      get() = _builder.getLsn()
      @JvmName("setLsn")
      set(value) {
        _builder.setLsn(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 2;</code>
     */
    public fun clearLsn() {
      _builder.clearLsn()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 2;</code>
     * @return Whether the lsn field is set.
     */
    public fun hasLsn(): kotlin.Boolean {
      return _builder.hasLsn()
    }

    /**
     * <pre>
     * this is an optional field if source have to store some additional info for fixing LSN position
     * </pre>
     *
     * <code>bytes replication_state = 3;</code>
     */
    public var replicationState: com.google.protobuf.ByteString
      @JvmName("getReplicationState")
      get() = _builder.getReplicationState()
      @JvmName("setReplicationState")
      set(value) {
        _builder.setReplicationState(value)
      }
    /**
     * <pre>
     * this is an optional field if source have to store some additional info for fixing LSN position
     * </pre>
     *
     * <code>bytes replication_state = 3;</code>
     */
    public fun clearReplicationState() {
      _builder.clearReplicationState()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRsp.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.FixLsnRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRsp =
  yandexcloud.datatransfer.dtextension.v0_2.source.FixLsnRspKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRspOrBuilder.resultOrNull: yandexcloud.datatransfer.dtextension.v0_2.Common.Result?
  get() = if (hasResult()) getResult() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnRspOrBuilder.lsnOrNull: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue?
  get() = if (hasLsn()) getLsn() else null

