//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializereadControlItemReq")
public inline fun readControlItemReq(block: yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq.newBuilder()).apply { block() }._build()
public object ReadControlItemReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.InitConnectionReq init_connection_req = 1;</code>
     */
    public var initConnectionReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.InitConnectionReq
      @JvmName("getInitConnectionReq")
      get() = _builder.getInitConnectionReq()
      @JvmName("setInitConnectionReq")
      set(value) {
        _builder.setInitConnectionReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.InitConnectionReq init_connection_req = 1;</code>
     */
    public fun clearInitConnectionReq() {
      _builder.clearInitConnectionReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.InitConnectionReq init_connection_req = 1;</code>
     * @return Whether the initConnectionReq field is set.
     */
    public fun hasInitConnectionReq(): kotlin.Boolean {
      return _builder.hasInitConnectionReq()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemReq data_item_req = 2;</code>
     */
    public var dataItemReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DataItemReq
      @JvmName("getDataItemReq")
      get() = _builder.getDataItemReq()
      @JvmName("setDataItemReq")
      set(value) {
        _builder.setDataItemReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemReq data_item_req = 2;</code>
     */
    public fun clearDataItemReq() {
      _builder.clearDataItemReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemReq data_item_req = 2;</code>
     * @return Whether the dataItemReq field is set.
     */
    public fun hasDataItemReq(): kotlin.Boolean {
      return _builder.hasDataItemReq()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CursorReq cursor_req = 3;</code>
     */
    public var cursorReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorReq
      @JvmName("getCursorReq")
      get() = _builder.getCursorReq()
      @JvmName("setCursorReq")
      set(value) {
        _builder.setCursorReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CursorReq cursor_req = 3;</code>
     */
    public fun clearCursorReq() {
      _builder.clearCursorReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CursorReq cursor_req = 3;</code>
     * @return Whether the cursorReq field is set.
     */
    public fun hasCursorReq(): kotlin.Boolean {
      return _builder.hasCursorReq()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.SplitReq split_req = 4;</code>
     */
    public var splitReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.SplitReq
      @JvmName("getSplitReq")
      get() = _builder.getSplitReq()
      @JvmName("setSplitReq")
      set(value) {
        _builder.setSplitReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.SplitReq split_req = 4;</code>
     */
    public fun clearSplitReq() {
      _builder.clearSplitReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.SplitReq split_req = 4;</code>
     * @return Whether the splitReq field is set.
     */
    public fun hasSplitReq(): kotlin.Boolean {
      return _builder.hasSplitReq()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.BeginSnapshotReq begin_snapshot_req = 5;</code>
     */
    public var beginSnapshotReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.BeginSnapshotReq
      @JvmName("getBeginSnapshotReq")
      get() = _builder.getBeginSnapshotReq()
      @JvmName("setBeginSnapshotReq")
      set(value) {
        _builder.setBeginSnapshotReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.BeginSnapshotReq begin_snapshot_req = 5;</code>
     */
    public fun clearBeginSnapshotReq() {
      _builder.clearBeginSnapshotReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.BeginSnapshotReq begin_snapshot_req = 5;</code>
     * @return Whether the beginSnapshotReq field is set.
     */
    public fun hasBeginSnapshotReq(): kotlin.Boolean {
      return _builder.hasBeginSnapshotReq()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DoneSnapshotReq done_snapshot_req = 6;</code>
     */
    public var doneSnapshotReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneSnapshotReq
      @JvmName("getDoneSnapshotReq")
      get() = _builder.getDoneSnapshotReq()
      @JvmName("setDoneSnapshotReq")
      set(value) {
        _builder.setDoneSnapshotReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DoneSnapshotReq done_snapshot_req = 6;</code>
     */
    public fun clearDoneSnapshotReq() {
      _builder.clearDoneSnapshotReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DoneSnapshotReq done_snapshot_req = 6;</code>
     * @return Whether the doneSnapshotReq field is set.
     */
    public fun hasDoneSnapshotReq(): kotlin.Boolean {
      return _builder.hasDoneSnapshotReq()
    }
    public val controlItemReqCase: yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq.ControlItemReqCase
      @JvmName("getControlItemReqCase")
      get() = _builder.getControlItemReqCase()

    public fun clearControlItemReq() {
      _builder.clearControlItemReq()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReqOrBuilder.initConnectionReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.InitConnectionReq?
  get() = if (hasInitConnectionReq()) getInitConnectionReq() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReqOrBuilder.dataItemReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DataItemReq?
  get() = if (hasDataItemReq()) getDataItemReq() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReqOrBuilder.cursorReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorReq?
  get() = if (hasCursorReq()) getCursorReq() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReqOrBuilder.splitReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.SplitReq?
  get() = if (hasSplitReq()) getSplitReq() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReqOrBuilder.beginSnapshotReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.BeginSnapshotReq?
  get() = if (hasBeginSnapshotReq()) getBeginSnapshotReq() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReqOrBuilder.doneSnapshotReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneSnapshotReq?
  get() = if (hasDoneSnapshotReq()) getDoneSnapshotReq() else null

