//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializereadControlItemRsp")
public inline fun readControlItemRsp(block: yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRsp =
  yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemRspKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRsp.newBuilder()).apply { block() }._build()
public object ReadControlItemRspKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRsp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRsp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRsp = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.InitConnectionRsp init_connection_rsp = 1;</code>
     */
    public var initConnectionRsp: yandexcloud.datatransfer.dtextension.v0_2.source.Control.InitConnectionRsp
      @JvmName("getInitConnectionRsp")
      get() = _builder.getInitConnectionRsp()
      @JvmName("setInitConnectionRsp")
      set(value) {
        _builder.setInitConnectionRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.InitConnectionRsp init_connection_rsp = 1;</code>
     */
    public fun clearInitConnectionRsp() {
      _builder.clearInitConnectionRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.InitConnectionRsp init_connection_rsp = 1;</code>
     * @return Whether the initConnectionRsp field is set.
     */
    public fun hasInitConnectionRsp(): kotlin.Boolean {
      return _builder.hasInitConnectionRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemRsp data_item_rsp = 2;</code>
     */
    public var dataItemRsp: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DataItemRsp
      @JvmName("getDataItemRsp")
      get() = _builder.getDataItemRsp()
      @JvmName("setDataItemRsp")
      set(value) {
        _builder.setDataItemRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemRsp data_item_rsp = 2;</code>
     */
    public fun clearDataItemRsp() {
      _builder.clearDataItemRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemRsp data_item_rsp = 2;</code>
     * @return Whether the dataItemRsp field is set.
     */
    public fun hasDataItemRsp(): kotlin.Boolean {
      return _builder.hasDataItemRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CursorRsp cursor_rsp = 3;</code>
     */
    public var cursorRsp: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp
      @JvmName("getCursorRsp")
      get() = _builder.getCursorRsp()
      @JvmName("setCursorRsp")
      set(value) {
        _builder.setCursorRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CursorRsp cursor_rsp = 3;</code>
     */
    public fun clearCursorRsp() {
      _builder.clearCursorRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CursorRsp cursor_rsp = 3;</code>
     * @return Whether the cursorRsp field is set.
     */
    public fun hasCursorRsp(): kotlin.Boolean {
      return _builder.hasCursorRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.SplitRsp split_rsp = 4;</code>
     */
    public var splitRsp: yandexcloud.datatransfer.dtextension.v0_2.source.Control.SplitRsp
      @JvmName("getSplitRsp")
      get() = _builder.getSplitRsp()
      @JvmName("setSplitRsp")
      set(value) {
        _builder.setSplitRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.SplitRsp split_rsp = 4;</code>
     */
    public fun clearSplitRsp() {
      _builder.clearSplitRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.SplitRsp split_rsp = 4;</code>
     * @return Whether the splitRsp field is set.
     */
    public fun hasSplitRsp(): kotlin.Boolean {
      return _builder.hasSplitRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.BeginSnapshotRsp begin_snapshot_rsp = 5;</code>
     */
    public var beginSnapshotRsp: yandexcloud.datatransfer.dtextension.v0_2.source.Control.BeginSnapshotRsp
      @JvmName("getBeginSnapshotRsp")
      get() = _builder.getBeginSnapshotRsp()
      @JvmName("setBeginSnapshotRsp")
      set(value) {
        _builder.setBeginSnapshotRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.BeginSnapshotRsp begin_snapshot_rsp = 5;</code>
     */
    public fun clearBeginSnapshotRsp() {
      _builder.clearBeginSnapshotRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.BeginSnapshotRsp begin_snapshot_rsp = 5;</code>
     * @return Whether the beginSnapshotRsp field is set.
     */
    public fun hasBeginSnapshotRsp(): kotlin.Boolean {
      return _builder.hasBeginSnapshotRsp()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DoneSnapshotRsp done_snapshot_rsp = 6;</code>
     */
    public var doneSnapshotRsp: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneSnapshotRsp
      @JvmName("getDoneSnapshotRsp")
      get() = _builder.getDoneSnapshotRsp()
      @JvmName("setDoneSnapshotRsp")
      set(value) {
        _builder.setDoneSnapshotRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DoneSnapshotRsp done_snapshot_rsp = 6;</code>
     */
    public fun clearDoneSnapshotRsp() {
      _builder.clearDoneSnapshotRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DoneSnapshotRsp done_snapshot_rsp = 6;</code>
     * @return Whether the doneSnapshotRsp field is set.
     */
    public fun hasDoneSnapshotRsp(): kotlin.Boolean {
      return _builder.hasDoneSnapshotRsp()
    }
    public val controlItemRspCase: yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRsp.ControlItemRspCase
      @JvmName("getControlItemRspCase")
      get() = _builder.getControlItemRspCase()

    public fun clearControlItemRsp() {
      _builder.clearControlItemRsp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRsp.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRsp =
  yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemRspKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRspOrBuilder.initConnectionRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.InitConnectionRsp?
  get() = if (hasInitConnectionRsp()) getInitConnectionRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRspOrBuilder.dataItemRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DataItemRsp?
  get() = if (hasDataItemRsp()) getDataItemRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRspOrBuilder.cursorRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CursorRsp?
  get() = if (hasCursorRsp()) getCursorRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRspOrBuilder.splitRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.SplitRsp?
  get() = if (hasSplitRsp()) getSplitRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRspOrBuilder.beginSnapshotRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.BeginSnapshotRsp?
  get() = if (hasBeginSnapshotRsp()) getBeginSnapshotRsp() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemRspOrBuilder.doneSnapshotRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DoneSnapshotRsp?
  get() = if (hasDoneSnapshotRsp()) getDoneSnapshotRsp() else null

