//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/source_service.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializereadReq")
public inline fun readReq(block: yandexcloud.datatransfer.dtextension.v0_2.source.ReadReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.ReadReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReq.newBuilder()).apply { block() }._build()
public object ReadReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReq = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Table table = 1;</code>
     */
    public var table: yandexcloud.datatransfer.dtextension.v0_2.Data.Table
      @JvmName("getTable")
      get() = _builder.getTable()
      @JvmName("setTable")
      set(value) {
        _builder.setTable(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Table table = 1;</code>
     */
    public fun clearTable() {
      _builder.clearTable()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Table table = 1;</code>
     * @return Whether the table field is set.
     */
    public fun hasTable(): kotlin.Boolean {
      return _builder.hasTable()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Cursor cursor = 2;</code>
     */
    public var cursor: yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor
      @JvmName("getCursor")
      get() = _builder.getCursor()
      @JvmName("setCursor")
      set(value) {
        _builder.setCursor(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Cursor cursor = 2;</code>
     */
    public fun clearCursor() {
      _builder.clearCursor()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Cursor cursor = 2;</code>
     * @return Whether the cursor field is set.
     */
    public fun hasCursor(): kotlin.Boolean {
      return _builder.hasCursor()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemReq control_item_req = 3;</code>
     */
    public var controlItemReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq
      @JvmName("getControlItemReq")
      get() = _builder.getControlItemReq()
      @JvmName("setControlItemReq")
      set(value) {
        _builder.setControlItemReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemReq control_item_req = 3;</code>
     */
    public fun clearControlItemReq() {
      _builder.clearControlItemReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.ReadControlItemReq control_item_req = 3;</code>
     * @return Whether the controlItemReq field is set.
     */
    public fun hasControlItemReq(): kotlin.Boolean {
      return _builder.hasControlItemReq()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.ReadReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.ReadReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReqOrBuilder.tableOrNull: yandexcloud.datatransfer.dtextension.v0_2.Data.Table?
  get() = if (hasTable()) getTable() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReqOrBuilder.cursorOrNull: yandexcloud.datatransfer.dtextension.v0_2.Common.Cursor?
  get() = if (hasCursor()) getCursor() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.ReadReqOrBuilder.controlItemReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.ReadControlItemReq?
  get() = if (hasControlItemReq()) getControlItemReq() else null

