//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/control.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializestreamControlItemReq")
public inline fun streamControlItemReq(block: yandexcloud.datatransfer.dtextension.v0_2.source.StreamControlItemReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.StreamControlItemReqKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReq.newBuilder()).apply { block() }._build()
public object StreamControlItemReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReq = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemReq data_item_req = 1;</code>
     */
    public var dataItemReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DataItemReq
      @JvmName("getDataItemReq")
      get() = _builder.getDataItemReq()
      @JvmName("setDataItemReq")
      set(value) {
        _builder.setDataItemReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemReq data_item_req = 1;</code>
     */
    public fun clearDataItemReq() {
      _builder.clearDataItemReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.DataItemReq data_item_req = 1;</code>
     * @return Whether the dataItemReq field is set.
     */
    public fun hasDataItemReq(): kotlin.Boolean {
      return _builder.hasDataItemReq()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.FixLsnReq fix_lsn_req = 2;</code>
     */
    public var fixLsnReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnReq
      @JvmName("getFixLsnReq")
      get() = _builder.getFixLsnReq()
      @JvmName("setFixLsnReq")
      set(value) {
        _builder.setFixLsnReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.FixLsnReq fix_lsn_req = 2;</code>
     */
    public fun clearFixLsnReq() {
      _builder.clearFixLsnReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.FixLsnReq fix_lsn_req = 2;</code>
     * @return Whether the fixLsnReq field is set.
     */
    public fun hasFixLsnReq(): kotlin.Boolean {
      return _builder.hasFixLsnReq()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CheckLsnReq check_lsn_req = 3;</code>
     */
    public var checkLsnReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq
      @JvmName("getCheckLsnReq")
      get() = _builder.getCheckLsnReq()
      @JvmName("setCheckLsnReq")
      set(value) {
        _builder.setCheckLsnReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CheckLsnReq check_lsn_req = 3;</code>
     */
    public fun clearCheckLsnReq() {
      _builder.clearCheckLsnReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.CheckLsnReq check_lsn_req = 3;</code>
     * @return Whether the checkLsnReq field is set.
     */
    public fun hasCheckLsnReq(): kotlin.Boolean {
      return _builder.hasCheckLsnReq()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.RewindLsnReq rewind_lsn_req = 4;</code>
     */
    public var rewindLsnReq: yandexcloud.datatransfer.dtextension.v0_2.source.Control.RewindLsnReq
      @JvmName("getRewindLsnReq")
      get() = _builder.getRewindLsnReq()
      @JvmName("setRewindLsnReq")
      set(value) {
        _builder.setRewindLsnReq(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.RewindLsnReq rewind_lsn_req = 4;</code>
     */
    public fun clearRewindLsnReq() {
      _builder.clearRewindLsnReq()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.RewindLsnReq rewind_lsn_req = 4;</code>
     * @return Whether the rewindLsnReq field is set.
     */
    public fun hasRewindLsnReq(): kotlin.Boolean {
      return _builder.hasRewindLsnReq()
    }
    public val controlItemReqCase: yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReq.ControlItemReqCase
      @JvmName("getControlItemReqCase")
      get() = _builder.getControlItemReqCase()

    public fun clearControlItemReq() {
      _builder.clearControlItemReq()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReq.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.StreamControlItemReqKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReq =
  yandexcloud.datatransfer.dtextension.v0_2.source.StreamControlItemReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReqOrBuilder.dataItemReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.DataItemReq?
  get() = if (hasDataItemReq()) getDataItemReq() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReqOrBuilder.fixLsnReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.FixLsnReq?
  get() = if (hasFixLsnReq()) getFixLsnReq() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReqOrBuilder.checkLsnReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.CheckLsnReq?
  get() = if (hasCheckLsnReq()) getCheckLsnReq() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemReqOrBuilder.rewindLsnReqOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.RewindLsnReq?
  get() = if (hasRewindLsnReq()) getRewindLsnReq() else null

