//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api/v0_2/source/source_service.proto

package yandexcloud.datatransfer.dtextension.v0_2.source;

@kotlin.jvm.JvmName("-initializestreamRsp")
public inline fun streamRsp(block: yandexcloud.datatransfer.dtextension.v0_2.source.StreamRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRsp =
  yandexcloud.datatransfer.dtextension.v0_2.source.StreamRspKt.Dsl._create(yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRsp.newBuilder()).apply { block() }._build()
public object StreamRspKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRsp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRsp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRsp = _builder.build()

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     */
    public var result: yandexcloud.datatransfer.dtextension.v0_2.Common.Result
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.Result result = 1;</code>
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 2;</code>
     */
    public var lsn: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue
      @JvmName("getLsn")
      get() = _builder.getLsn()
      @JvmName("setLsn")
      set(value) {
        _builder.setLsn(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 2;</code>
     */
    public fun clearLsn() {
      _builder.clearLsn()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.ColumnValue lsn = 2;</code>
     * @return Whether the lsn field is set.
     */
    public fun hasLsn(): kotlin.Boolean {
      return _builder.hasLsn()
    }

    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.StreamControlItemRsp control_item_rsp = 3;</code>
     */
    public var controlItemRsp: yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemRsp
      @JvmName("getControlItemRsp")
      get() = _builder.getControlItemRsp()
      @JvmName("setControlItemRsp")
      set(value) {
        _builder.setControlItemRsp(value)
      }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.StreamControlItemRsp control_item_rsp = 3;</code>
     */
    public fun clearControlItemRsp() {
      _builder.clearControlItemRsp()
    }
    /**
     * <code>.yandexcloud.datatransfer.dtextension.v0_2.source.StreamControlItemRsp control_item_rsp = 3;</code>
     * @return Whether the controlItemRsp field is set.
     */
    public fun hasControlItemRsp(): kotlin.Boolean {
      return _builder.hasControlItemRsp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRsp.copy(block: yandexcloud.datatransfer.dtextension.v0_2.source.StreamRspKt.Dsl.() -> kotlin.Unit): yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRsp =
  yandexcloud.datatransfer.dtextension.v0_2.source.StreamRspKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRspOrBuilder.resultOrNull: yandexcloud.datatransfer.dtextension.v0_2.Common.Result?
  get() = if (hasResult()) getResult() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRspOrBuilder.lsnOrNull: yandexcloud.datatransfer.dtextension.v0_2.Data.ColumnValue?
  get() = if (hasLsn()) getLsn() else null

val yandexcloud.datatransfer.dtextension.v0_2.source.SourceServiceOuterClass.StreamRspOrBuilder.controlItemRspOrNull: yandexcloud.datatransfer.dtextension.v0_2.source.Control.StreamControlItemRsp?
  get() = if (hasControlItemRsp()) getControlItemRsp() else null

